# Generated by Django 4.2.4 on 2023-10-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTubeWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ans1',
            old_name='qn1',
            new_name='options',
        ),
    ]
