# Generated by Django 4.2.4 on 2023-10-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTubeWebsite', '0002_rename_qn1_ans1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='qn2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ans2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthTubeWebsite.qn2')),
            ],
        ),
    ]
