# Generated by Django 4.2.4 on 2023-10-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTubeWebsite', '0006_qn5_ans5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
    ]
