# Generated by Django 4.2.4 on 2023-10-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTubeWebsite', '0008_custommodelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='qn7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
